backend:
  name: test-repo

media_folder: static/assets
public_folder: assets

collections:
  - name: articles
    label: Articles
    folder: articles
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: excerpt, label: excerpt, widget: text }
      - label: "Tags"
        name: "tags"
        widget: "list"
        field:
          - { name: php, label: php }
      - { name: body, label: Body, widget: markdown }
  - name: projects
    label: Projects
    folder: projects
    create: true
    fields:
      - { name: path, label: Path }
      - { name: title, label: Title }
      - { name: short_description, label: "Short Description", widget: text }
      - { label: "Thumbnail", name: "thumbnail", widget: "image", required: true }
      - { name: body, label: Body, widget: markdown }
